volumes:
  caddy_data:
  caddy_config:
  db:

services:
  server:
    build: .
    ports:
      - "8080:80"
      - "8443:443"
      - "23517:23517"  # Ray debugging port
    volumes:
      - .:/app:cached
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - FRANKENPHP_CONFIG=worker ./public/index.php
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Required for Ray to connect to host
    restart: unless-stopped
    deploy: 
      resources:
        limits:
          memory: 2GB
        reservations:
          memory: 2GB
    
  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=headfirst_db
      - MYSQL_USER=headfirst_user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - db:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 1GB

