version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/app:cached
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - FRANKENPHP_CONFIG=worker ./public/index.php
    restart: unless-stopped
    deploy: 
      resources:
        limits:
          memory: 2GB
        reservations:
          memory: 2GB
          
  browser-sync:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"  # Browser-sync UI
      - "3001:3001"  # Browser-sync proxy
    command: >
      sh -c "
        npm install -g browser-sync &&
        browser-sync start 
          --proxy 'app:80' 
          --files 'public/**/*.php,public/**/*.html,public/**/*.css,public/**/*.js'
          --host 0.0.0.0
          --port 3000
          --ui-port 3001
          --no-open
      "
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
