volumes:
  caddy_data:
  caddy_config:
  db:
  db_test:

services:
  server:
    build: .
    ports:
      - "8080:80"
      - "8443:443"
      # - "23517:23517"  # Ray debugging port
    volumes:
      - .:/app:cached
      - caddy_data:/data
      - caddy_config:/config
      - ./config/php.ini:/usr/local/etc/php/conf.d/99-custom.ini
    environment:
      - FRANKENPHP_CONFIG=worker ./public/index.php
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"  # Required for Ray to connect to host
    restart: unless-stopped
    deploy: 
      resources:
        limits:
          memory: 2GB
        reservations:
          memory: 2GB
    
  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 1GB
  db_test:
    image: mysql:latest
    ports:
      - '3307:3306'
    environment:
      - MYSQL_DATABASE=${DB_DATABASE_TEST}
      - MYSQL_USER=${DB_USERNAME_TEST}
      - MYSQL_PASSWORD=${DB_PASSWORD_TEST}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD_TEST}
    volumes:
      - db_test:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 1GB

