name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: headfirst_db_test
          MYSQL_USER: headfirst_user_test
          MYSQL_PASSWORD: password_test
          MYSQL_ROOT_PASSWORD: root_password_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: pdo, pdo_mysql, mbstring
          coverage: none

      - name: Verify PHP version
        run: php -v

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Copy environment file
        run: cp .env .env.testing || echo "No .env file to copy"

      - name: Run migrations
        run: vendor/bin/phinx migrate -e testing
        env:
          DB_HOST_TEST: 127.0.0.1
          DB_DATABASE_TEST: headfirst_db_test
          DB_USERNAME_TEST: headfirst_user_test
          DB_PASSWORD_TEST: password_test
          DB_ROOT_PASSWORD_TEST: root_password_test

      - name: Run tests
        run: vendor/bin/phpunit --testdox
        env:
          DB_HOST_TEST: 127.0.0.1
          DB_DATABASE_TEST: headfirst_db_test
          DB_USERNAME_TEST: headfirst_user_test
          DB_PASSWORD_TEST: password_test
          DB_ROOT_PASSWORD_TEST: root_password_test
